version: "3.7"

networks:
  proxy:
    external: true

services:
  chart-screener:
    image: $CI_REGISTRY_IMAGE/app:$DEPLOY_TAG
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      labels:
        - "traefik.http.routers.${STACK_NAME}.rule=(Host(`${TRAEFIK_HOST}`) && PathPrefix(`${TRAEFIK_PATH}`))"
        - "traefik.http.services.${STACK_NAME}.loadbalancer.server.port=3050"
        - "traefik.http.middlewares.strip-${STACK_NAME}.stripprefix.prefixes=${TRAEFIK_PATH}"
        - "traefik.http.routers.${STACK_NAME}.middlewares=strip-${STACK_NAME}"
        - "traefik.http.routers.${STACK_NAME}.entrypoints=websecure"
        - "traefik.http.routers.${STACK_NAME}.tls=true"
        - "traefik.http.routers.${STACK_NAME}.tls.certresolver=letsencrypt"
    networks:
      - proxy
