version: "3.7"

networks:
  proxy:
    external: true

services:
  chart-screener:
    image: $CI_REGISTRY_IMAGE/app:$DEPLOY_TAG
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      labels:
        traefik.http.routers.chart-screener.rule:  (Host(`${TRAEFIK_HOST}`) && PathPrefix(`${TRAEFIK_PATH}`))
        traefik.http.services.chart-screener.loadbalancer.server.port: 3050
        traefik.http.routers.chart-screener.entrypoints: websecure
        traefik.http.routers.chart-screener.tls: "true"
        traefik.http.routers.chart-screener.tls.certresolver: letsencrypt
        traefik.http.routers.chart-screener.middlewares: stripper-chart
        traefik.http.middlewares.stripper-chart.stripprefix.prefixes: /nlu-labs/chart-screener
    networks:
      - proxy
